package com.fooddelivery.api.dto;

import com.fooddelivery.api.entity.PaymentMethod;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * Represents the data required to initiate a payment.
 */
public class PaymentRequest {

    /**
     * ID of the order for which the payment is being initiated.
     */
    @NotNull
    private Long orderId;

    /**
     * Payment method selected by the customer.
     */
    @NotNull
    private PaymentMethod paymentMethod;

    /**
     * Unique key generated by the client for preventing
     * duplicate payment requests.
     */
    @NotBlank
    private String idempotencyKey;

    // Generate getters and setters using IntelliJ.

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }
}