package com.fooddelivery.api.dto;

import com.fooddelivery.api.entity.PaymentMethod;
import com.fooddelivery.api.entity.PaymentStatus;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents the payment information returned to the client.
 */
public class PaymentResponse {

    /**
     * Unique identifier of the payment record.
     */
    private Long id;

    /**
     * ID of the associated order.
     */
    private Long orderId;

    /**
     * Unique transaction identifier generated by MyFood.
     */
    private String transactionId;

    /**
     * Amount involved in the payment.
     */
    private BigDecimal amount;

    /**
     * Payment method used for the transaction.
     */
    private PaymentMethod paymentMethod;

    /**
     * Current status of the payment.
     */
    private PaymentStatus paymentStatus;

    /**
     * Timestamp when the payment was created.
     */
    private LocalDateTime createdAt;

    /**
     * Timestamp when the payment was last updated.
     */
    private LocalDateTime updatedAt;

    // Generate getters and setters using IntelliJ.

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}