package com.fooddelivery.api.dto;

/**
 * Represents the information required by the frontend
 * to initiate a payment with an external payment gateway.
 */
public class PaymentInitiationResponse {

    /**
     * URL of the external payment gateway.
     */
    private String paymentUrl;

    /**
     * Merchant key used by the payment gateway.
     */
    private String key;

    /**
     * Unique transaction ID generated by MyFood.
     */
    private String transactionId;

    /**
     * Amount to be paid.
     */
    private String amount;

    /**
     * Product information associated with the payment.
     */
    private String productInfo;

    /**
     * Customer's first name.
     */
    private String firstName;

    /**
     * Customer's email address.
     */
    private String email;

    /**
     * Customer's phone number.
     */
    private String phone;

    /**
     * Hash generated by the backend.
     */
    private String hash;

    /**
     * URL to which PayU sends a successful payment response.
     */
    private String successUrl;

    /**
     * URL to which PayU sends a failed payment response.
     */
    private String failureUrl;

    // Generate getters and setters using IntelliJ.

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getPaymentUrl() {
        return paymentUrl;
    }

    public void setPaymentUrl(String paymentUrl) {
        this.paymentUrl = paymentUrl;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getProductInfo() {
        return productInfo;
    }

    public void setProductInfo(String productInfo) {
        this.productInfo = productInfo;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getSuccessUrl() {
        return successUrl;
    }

    public void setSuccessUrl(String successUrl) {
        this.successUrl = successUrl;
    }

    public String getFailureUrl() {
        return failureUrl;
    }

    public void setFailureUrl(String failureUrl) {
        this.failureUrl = failureUrl;
    }
}