spring.application.name=food-delivery-api

spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
# PayU Test Credentials
payu.merchant-key=${TEST_PAYU_MERCHANT_KEY}
payu.merchant-salt=${TEST_PAYU_MERCHANT_SALT}
payu.payment-url=https://apitest.payu.in/v2/payments
payu.verify-url=https://test.payu.in/v3/transaction
spring.jpa.hibernate.ddl-auto=update
app.frontend-url=http://localhost:4200

logging.level.org.springframework.security=DEBUG